### ISSUE TITLE
Issues with GET command

### ISSUE THREAD

**Issue by JacksonChou** [blakiseskream/workdayr#1] opened 2019-03-28 23:48 UTC
I wasn't able to install the function through your instructions in the readme description but was able to create the function looking in your script

I'm getting a curl error:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer
```

Have you seen or experienced this before?

**Comment by blakiseskream** [comment] 2019-03-29 17:40
hi @JacksonChou could you provide a [reprex](https://github.com/tidyverse/reprex) for the install and the full code you are running? 

The `curl::curl_fetch_memory` error is a [known issue](https://github.com/r-lib/httr/issues/568) with `httr` when querying the Workday API.

To circumvent it I add [write_disk](https://github.com/blakiseskream/workdayr/blob/4782fe0395983af00d494d30b8ef173896fcb2a8/R/get_workday_report.R#L57) and parse the csv in the request as it says in the docs,

> The httr::GET() request is wrapped in a purrr::safely() to write the file to disk regardless of error.

It will still tell you the error occurred but should return the desired result.

**Comment by JacksonChou** [comment] 2019-03-29 20:53
Thanks @blakiseskream, I got the function to work and went ahead with reading the `report_path` despite seeing the warning message as you suggested.

One thing I suggest editing is adding the `endpoint` as an argument in `get_workday_report()` because in your package the endpoint is hardcoded as:

`# create url`
`  endpoint <- 'https://wd5-services1.myworkday.com/ccx/service/customreport2/'`
`  query_url <- paste0(
    endpoint
    , organization
    , "/"
    , report_name
  )`

However, the URL for my Workday API starts off as:
 ` endpoint <- 'https://services1.myworkday.com/ccx/service/customreport2/'`

So I had to edit the default `endpoint`, otherwise I'd keep getting `500 status error` from `httr::GET()`.

**Comment by blakiseskream** [comment] 2019-06-26 23:29
Fixed with https://github.com/blakiseskream/workdayr/commit/3f020f1b2fd48db34a94b41a70f94db403f283c0

**Closed as completed by blakiseskream** 2019-06-26 23:29 UTC
Labels: enhancement

**Comment by jonlinca** [comment] 2020-07-15 19:47
I was using your current code internally at my org (thank you very much for it). For us, the error "Failure when receiving data from the peer" was caused by using the Schannel SSL backend. 

To debug it, I first ran GET(..., verbose()), which returned several Schannel errors related to the error. I then checked `curl_version()$ssl_version` which led me to realize Schannel was being used as primary, while OpenSSL was available but was not used.

Putting the line `CURL_SSL_BACKEND=openssl` within the .Renviron file solved that problem. Thanks @blakiseskream.
